<?php	// Edit this file to change the Wiki! script language

	$index = "index";		
	$all = "all nodes";
	$edit = "edit";
	$login = "log in";
	$logout = "log out"; 
	$return = "return";

	$loggedin = "You Are Now Logged In As ";	// note trailing space	
	$loggedin_d = "'tis true.";
	$loggedout = "Logged Out";
	$loggedout_d = "You are no longer logged in.";
	$invlogin = "Authorisation Required";
	$invlogin_d = "You must be logged in to edit a node.";
	$invpass = "Invalid Password";
	$invpass_d = "Don't try to be original here.";
	$invparam = "Invalid Parameters";
	$invparam_d = "No node title given";
	$success = "Success";
	$success_d = " has been updated.";		// leading space
	$nodelist = "Node List";	

	$revhistory = "<b>Revision History</b>";
	$empty = "<center><i>This node is currently empty.</i></center>";
	$cookies = "Note: you must have cookies enabled.";
	$track = "Track revision for this node?";
?>