<?php	// Edit this file to change the Wiki! script language

	$index = "Startseite";
	$all = "Alle Einträge";
	$edit = "Bearbeiten";
	$login = "Einloggen";
	$logout = "Ausloggen";
	$return = "Zurück";

	$loggedin = "Du bist angemeldet als ";	// note trailing space
	$loggedin_d = "Viel Spaß im Wiki.";
	$loggedout = "Ausgeloggt";
	$loggedout_d = "Bis zum nächsten Mal";
	$invlogin = "Access Denied";
	$invlogin_d = "Bitte einloggen um diesen Eintrag anzusehen.";
	$invpass = "Ungültiges Passwort";
	$invpass_d = "Auf ein Neues!";
	$invparam = "Ungültige Parameter";
	$invparam_d = "Es wurde kein Titel für den Eintrag angegeben.";
	$success = "Aktualisierung";
	$success_d = " wurde erfolgreich aktualisiert.";		// leading space
	$nodelist = "Vorhandene Einträge";

	$revhistory = "<b>Änderungen</b>";
	$empty = "<center><i>Auf Bearbeiten klicken, um den Eintrag zu ändern.</i></center>";
	$cookies = "Hinweis: Diese Seite benötigt Cookies.";
	$track = "Änderungen protokollieren?";
?>